### ISSUE TITLE
Filament Shield implementation error

### ISSUE THREAD

**Issue by z00f** [kenepa/resource-lock#13]
Hi.
Does the plugin has Filament Shield implementation?
https://github.com/bezhanSalleh/filament-shield

It thows an error

![Screenshot from 2023-07-01 11-50-16](https://github.com/kenepa/resource-lock/assets/34635749/f171cc78-0448-402d-8d00-f19f7f319f1a)

**Comment by Jehizkia** [comment]
Well it has no specific implementation for the filament shield plugin, but I'll look into it!

**Comment by robertosanval** [comment]
I'm trying to use it with Filament Shield too but my error is when I try to edit a Role:

`Cannot assign bool to property Filament\Resources\Pages\EditRecord::$data of type ?array`

**Comment by Jehizkia** [comment]
@robertosanval, I haven't used Shield yet, but I'll try to move it up on my list to check it out. If you have any ideas, feel free to make a pull request.

**Comment by eelco2k** [comment]
i'm having the same issue:

debugbar gives me little more info:

```
Cannot assign bool to property Filament\Resources\Pages\EditRecord::$data of type ?array

./vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php#406
TypeError
    protected function setComponentPropertyAwareOfTypes($component, $property, $value)
    {
        try {
           $component->$property = $value;
        } catch (\TypeError $e) {
            // If an "int" is being set to empty string, unset the property (making it null).
            // This is common in the case of `wire:model`ing an int to a text field...
```

**Comment by eelco2k** [comment]
Also i see in the ResourceLockResource.php that there are only to policies:

canViewAny() and canDeleteAny() instead of the default filament permission_prefixes.

for now i disabled the resource permissions in filament-shield.php config file by adding ResourceLockResource to the resources array:

```
'exclude' => [
        'enabled' => true,

        'resources' => [
            'ResourceLockResource',
        ],
    ],
```

it also helps mitigating this issue: https://github.com/kenepa/resource-lock/issues/5

**Comment by eelco2k** [comment]
perhaps it has to do with the package name and the way Shield package identifies the permission name: 

see: https://github.com/bezhanSalleh/filament-shield?tab=readme-ov-file#configure-permission-identifier

the default permission identifier does some things with the string "Resource"

**Comment by eelco2k** [comment]
yes the package namespace of ResourceLock  in combination with the FilamentShield resource suffix for permissions makes this go wrong

You can fix it by adding this code to your AppServiceProvider.php boot() method:

```
FilamentShield::configurePermissionIdentifierUsing(fn ($resource) => return str($resource::getModel())->prepend('::')->toString());
```

This makes all your Resource permissions structure in the database column look like this:
for example:
```
view_any::Kenepa\ResourceLock\Resources\ResourceLockResource
```

**Comment by Jehizkia** [comment]
Thank you for figuring this out @eelco2k !

**Comment by eelco2k** [comment]
@Jehizkia Thanks!
