### ISSUE TITLE
Resource lock in not removed when leaving page on Safari

### ISSUE THREAD

**Issue by Jehizkia** [kenepa/resource-lock#14]
**Description**

 Resource lock not removed after visiting and leaving a resource in Safari browser.
Description: A user has reported an issue where the resource lock remains in place after they visit and leave a resource while using the Safari browser. According to the user's account, the resource lock should be removed automatically when they navigate away from the resource. However, in Safari, the lock remains intact even after leaving the resource.
Expected Behavior: The resource lock should be automatically removed when the user visits and then leaves a resource, regardless of the browser being used.
Steps to Reproduce:
	1.	Open Safari browser.
	2.	Visit a resource.
	3.	Navigate away from the resource.
	4.	Check if the resource lock is removed or still present.

**Comment by mackhankins** [comment]
Doesn't the lock remain for 10 minutes or something via the config setting?

**Comment by Jehizkia** [comment]
Yes, you're absolutely right. However, the person who raised the issue wanted the lock to be removed immediately on Safari browsers, just like in the other browsers. But Safari has poor support for the `onbeforeunload` function.
