### ISSUE TITLE
lock() method in HasLocks trait does not allow for other guard than default one ('web')

### ISSUE THREAD

**Issue by eelco2k** [kenepa/resource-lock#25]
When loggedIn as user with multiple guards configured and the user is not using the 'web' guard... auth()->user()-id  IS NULL.

so the auth() should add the ->guard() like so :

In the lock() method in the HasLocks.php trait file on line: 

```
$resourceLock->user_id = auth()->user()->id;
```

doesn't allow for an custom guard. So you should get the guard name of the current logged in user with this method for example:

```
/**
     * @return array|null
     */
    private function getCurrentAuthGuardName()
    {
        $guards = array_keys(config('auth.guards'));

        foreach ($guards as $guard) {
            if (app()['auth']->guard($guard)->check()) {
                return $guard;
            }
        }

        return null;
    }
```

then you could add this:

```
$guard = $this->getCurrentAuthGuardName();
$resourceLock->user_id = auth()->guard($guard)->user()->id;
```

Do the same for the other two functions in this Trait:

```
isLockedByCurrentUser()
```
and
```
lockCreatedByCurrentUser()
```

**Comment by Jehizkia** [comment]
Resolved by https://github.com/kenepa/resource-lock/pull/28
