### ISSUE TITLE
Allow custom/override the ResourceLockResource

### ISSUE THREAD

**Issue by eelco2k** [kenepa/resource-lock#26]
Now i believe it is not possible to use / override a custom Resource  (for example in the config).

in ResourceLockPlugin.php the resources array could be fetched from config variable .

in resource-lock.php add

```
use Kenepa\ResourceLock\Resources\ResourceLockResource;

 'resource' => [
    'class' => ResourceLockResource::class
 ]

```

and in the register function of ResourceLockPlugin.php

```
$panel->resources([
   config('resource-lock.resource.class', ResourceLockResource::class),
]);
```

**Comment by Jehizkia** [comment]
Fixed by pr https://github.com/kenepa/resource-lock/pull/27
