### ISSUE TITLE
Error with simple modal lock

### ISSUE THREAD

**Issue by adriaardila** [kenepa/resource-lock#29]
Hello, I'm getting this error when attempting to add the UsesSimpleResourceLock to a simple modal resource (ex. ManageUsers).

`[2024-01-25 13:31:54] local.ERROR: Declaration of Kenepa\ResourceLock\Resources\Pages\Concerns\UsesSimpleResourceLock::mountTableAction(string $name, ?string $record = null) must be compatible with Filament\Resources\Pages\ListRecords::mountTableAction(string $name, ?string $record = null, array $arguments = []): mixed {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Declaration of Kenepa\\ResourceLock\\Resources\\Pages\\Concerns\\UsesSimpleResourceLock::mountTableAction(string $name, ?string $record = null) must be compatible with Filament\\Resources\\Pages\\ListRecords::mountTableAction(string $name, ?string $record = null, array $arguments = []): mixed at /var/www/nudato-v2/vendor/kenepa/resource-lock/src/Resources/Pages/Concerns/UsesSimpleResourceLock.php:26)
[stacktrace]
#0 {main}
"} `

**Comment by Jehizkia** [comment]
@adriaardila Thanks!
