### ISSUE TITLE
Resource lock not working for modals

### ISSUE THREAD

**Issue by yipisit** [kenepa/resource-lock#33]
In our project we're depening on our modals.
Too bad we cannot use this plugin as it does not support locking modals (in our case specifically slideovers).
We hope to see this functionality working in the future to be able to use this plugin in all our applications.

**Comment by Jehizkia** [comment]
Hi @yipisit, with modals do you mean the simpleresource modals?

**Comment by Jehizkia** [comment]
Closed for now. Needs more information
