### ISSUE TITLE
Save from edit record dont work with filament 3.2.65

### ISSUE THREAD

**Issue by JayAyAre** [kenepa/resource-lock#34]
on version 3.2.65 the 'save' function by edit record have now 2 parameters:

before:
    public function save(bool $shouldRedirect = true): void
after:
save(bool $shouldRedirect = true, bool $shouldSendSavedNotification = true): void

u need to update de edit record.

**Comment by Jehizkia** [comment]
Thank you, this is resolved in https://github.com/kenepa/resource-lock/pull/35 . Please use resourcelock v2.0.9
