### ISSUE TITLE
Error using the UsesSimpleResourcesLock

### ISSUE THREAD

**Issue by dharen008** [kenepa/resource-lock#42]
im having error using the UsesSimpleResourcesLock
![image](https://github.com/kenepa/resource-lock/assets/109984612/505d1c15-8483-482b-b366-d810f55353a1)

use Kenepa\ResourceLock\Resources\Pages\Concerns\UsesSimpleResourceLock;
use UsesSimpleResourceLock;

Declaration of Kenepa\ResourceLock\Resources\Pages\Concerns\UsesSimpleResourceLock::mountTableAction(string $name, ?string $record = null): mixed must be compatible with Filament\Resources\Pages\ListRecords::mountTableAction(string $name, ?string $record = null, array $arguments = []): mixed

**Comment by Jehizkia** [comment]
Thanks for reporting!

**Comment by dharen008** [comment]
> Thanks for reporting!

Thank you for fixing it!

**Comment by reynaldorrm** [comment]
Hello, I'm also having an issue whenever I use the UsesSimpleResourceLock.
I'm getting a 404 not found prompt after deleting an item to my resource, and when trying to update/edit an item.
https://app.screencast.com/pVa20OdQp8xyk

**Comment by dharen008** [comment]
> Hello, I'm also having an issue whenever I use the UsesSimpleResourceLock. I'm getting a 404 not found prompt after deleting an item to my resource, and when trying to update/edit an item. https://app.screencast.com/pVa20OdQp8xyk

I have the same issue. I've disabled all my UsesSimpleResourceLock. Hopefully, @Jehizkia can fix it. Thank you in advance!

**Comment by Jehizkia** [comment]
I'll be looking to it. Thanks!
