### ISSUE TITLE
Possible language conflict with filament-shield

### ISSUE THREAD

**Issue by mackhankins** [kenepa/resource-lock#5]
![Screenshot 2023-04-09 at 2 35 59 PM](https://user-images.githubusercontent.com/2184080/230793105-51e21a9b-b3e3-4c64-ac0f-62f34ff0d96d.png)

https://github.com/bezhanSalleh/filament-shield

These inputs values disappear when I install the package.  When I remove it they come back.

**Comment by mackhankins** [comment]
I found a bandaid.  You can exclude it inside of the `config/filament-shield.php`.  Something is happening when it tries to parse this resource automatically.

```php
    'exclude' => [
        'enabled' => true,

        'pages' => [
            'Dashboard',
        ],

        'widgets' => [
            'AccountWidget', 'FilamentInfoWidget',
        ],

        'resources' => [
            'ResourceLockResource',
        ],
    ],
```

**Comment by MaxBernasconiCodes** [comment]
Yup , having the same issue, tnx for the baindaid there.

> I found a bandaid. You can exclude it inside of the `config/filament-shield.php`. Something is happening when it tries to parse this resource automatically.
> 
> ```
>     'exclude' => [
>         'enabled' => true,
> 
>         'pages' => [
>             'Dashboard',
>         ],
> 
>         'widgets' => [
>             'AccountWidget', 'FilamentInfoWidget',
>         ],
> 
>         'resources' => [
>             'ResourceLockResource',
>         ],
>     ],
> ```

**Comment by Jehizkia** [comment]
Fixed by : https://github.com/kenepa/resource-lock/pull/46
