### ISSUE TITLE
Considering Optimistic Locking?

### ISSUE THREAD

**Issue by fseesys** [kenepa/resource-lock#7]
https://github.com/reshadman/laravel-optimistic-locking

I believe your current mechanism is "pessimistic locking", it has its pros & cons.

Have you considered adding "optimistic locking" into your package? I think it would make it more robust.

Thanks.

**Comment by Jehizkia** [comment]
This is a great suggestion. Reading further into it it indeed seems like the package is using pessimistic locking. Regarding your suggestion to add optimistic locking could improve its robustness. I'll add it to the roadmap to work on. If you have any ideas for a implementation feel free to make a PR or suggestions! 😄

**Comment by Jehizkia** [comment]
Added to the roadmap
